#docker-compose.yml (Base)
version: '3.4'
services:
  lemonmongo:
    image: mongo
    volumes:
      - lemonmongovol:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME:
        value: lemon 
      - MONGO_INITDB_ROOT_PASSWORD:
        value: lemon
    networks:
      - lemoncode-challenge
    ports:
      - 27017:27017

volumes:
  - lemonmongovol    

networks:
  - lemoncode-challenge
    



