apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp00
spec:
  selector:
    matchLabels:
      app: todoapp00
  template:
    metadata:
      labels:
        app: todoapp00
    spec:
      containers:
        - name: todoapp00
          image: sitobusnan/todoapp
          env:
          - name: PORT
            value: '3000'
          - name: NODE_ENV
            value: 'development'
          containerPort: '3000'
