apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp00
spec:
  selector:
    matchLabels:
      app: todoapp00
      exercise: '00'
  template:
    metadata:
      labels:
        app: todoapp00
        exercise: '00'
    spec:
      containers:
        - name: todoapp00
          image: sitobusnan/todoapp
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
          env:
          - name: PORT
            value: '3000'
          - name: NODE_ENV
            value: 'development'
          containerPort: '3000'
