apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp00
spec:
  selector:
    matchLabels:
      app: todoapp00
      exercise: '00'
  template:
    metadata:
      labels:
        app: todoapp00
        exercise: '00'
    spec:
      containers:
        - name: todoapp00
          image: sitobusnan/todoapp
          ports:
            - containerPort: 3000          
          env:
          - name: PORT
            value: '3000'
          - name: NODE_ENV
            value: 'development'
